export * from './address.model';
export * from './department.model';
export * from './gender.model'
export * from './loginDetails.model';
export * from './role.model';
export * from './user.model';
export * from './userGroup.model';
export * from './register.model';
export * from './course.model';
export * from './semester.model';
export * from './sections.model';