# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
    branches:
      develop_2.0:
        - step:
           script:
             - git remote add sync https://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@github.com/Maanavar-2-0/devm20.git
             - git checkout develop_2.0
             - git pull    
             - git push sync develop_2.0
